[package]
edition = "2021"
name = "totp"
version = "0.2.0"

[dependencies]
base32 = "0.4"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
tempfile = "3.3"
