[package]
edition = "2021"
name = "totp"
version = "0.1.0"

[dependencies]
base32 = "0.4.0"
hmac = "0.12.1"
sha1 = "0.10.1"
sha2 = "0.10.2"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
tempfile = "3.3"
